let app;
let app_background;
let app_front;
let app_public;
let app_routes;
let app_services;
let dest;
let lib;
let model;
let path;
let relativeDestPath;
let relativeSrcPath;
let relativeTestPath;
let src;
let test;

path = require('path');

dest = './build';

src = './src';

test = './test';

lib = '/lib';

app = '/app';

model = '/model';

app_public = '/app/public';

app_front = '/app/public/front';

app_background = '/app/background';

app_routes = '/app/routes';

app_services = '/app/services';

relativeSrcPath = path.relative('.', src);

relativeDestPath = path.relative('.', dest);

relativeTestPath = path.relative('.', test);

module.exports = {
  dest,
  server_js_copy: {
    src: [`${src}/**/*.js`, `!${src}${app_front}/**/*.js`],
    dest,
  },
  coffee_app_public: {
    src: `${src + app_front}/**/*.coffee`,
    dest: `${dest + app_front}/js`,
  },
  jade_copy: {
    src: `${src + app}/views/**`,
    dest: `${dest + app}/views/`,
  },
  images_copy: {
    src: `${src + app_front}/images/**`,
    dest: `${dest + app_front}/images/`,
  },
  sass: {
    src: [`${src + app_front}/sass/**//!(_)*`],
    dest: `${dest + app_front}/css/`,
  },
  bower_css: {
    src: [
      'bower_components/font-awesome/css/font-awesome.min.css',
      'bower_components/bootstrap/dist/css/bootstrap.min.css',
      'bower_components/angular/angular-csp.css',
      'bower_components/angularjs-toaster/toaster.min.css',
      'bower_components/notie/dist/notie.css',
      'bower_components/animate.css/animate.css',
      'bower_components/cal-heatmap/cal-heatmap.css',
    ],
    dest: `${dest + app_front}/css/vendors/`,
  },
  bower_js: {
    src: [
      'bower_components/moment/moment.js',
      'bower_components/lodash/lodash.js',
      'bower_components/jquery/dist/jquery.js',
      'bower_components/bootstrap/dist/js/bootstrap.js',
      'bower_components/wow/dist/wow.js',
      'bower_components/notie/dist/notie.min.js',
      'bower_components/mousetrap/mousetrap.js',
      'bower_components/d3/d3.js',
      'bower_components/cal-heatmap/cal-heatmap.js',
    ],
    dest: `${dest + app_front}/js/vendors/`,
  },
  bower_angularjs: {
    src: [
      'bower_components/angular/angular.js',
      'bower_components/angular-route/angular-route.js',
      'bower_components/angular-animate/angular-animate.js',
      'bower_components/angular-sanitize/angular-sanitize.js',
      'bower_components/angular-touch/angular-touch.js',
      'bower_components/nginfinitescroll/build/ng-infinite-scroll.js',
      'bower_components/angulartics/dist/angulartics.min.js',
      'bower_components/angulartics-google-analytics/dist/angulartics-ga.min.js',
    ],
    dest: `${dest + app_front}/js/vendors/`,
  },
  bower_font: {
    src: ['bower_components/font-awesome/fonts/*'],
    dest: `${dest + app_front}/css/fonts/`,
  },
  rev: {
    src: [`${dest + app_front}/**/*.+(min.js|min.css|png|gif|jpg|jpeg|avif|webp|svg|woff|ico|gz)`],
    dest: `${dest + app_front}/`,
    manifestFileName: 'rev-manifest.json',
  },
  rev_replace: {
    src: `${dest + app}/views/**/*.jade`,
    dest: `${dest + app}/views`,
    prefix: 'front/',
  },
  mocha: {
    src: './test/**/*.coffee',
  },
  clean: {
    target: 'build/**/*',
    // targets: ['build/**/*'],
    // excludes: [
    //   '!build/script',
    //   '!build/script/*',
    //   '!build/script/crons',
    //   '!build/script/crons/*',
    //   '!build/script/crawl_batch',
    //   '!build/script/crawl_batch/*',
    //   '!build/script/crawl_batch/daily',
    //   '!build/script/crawl_batch/daily/*',
    //   '!build/script/crawl_batch/monthly',
    //   '!build/script/crawl_batch/monthly/*',
    //   '!build/script/crawl_batch/weekly',
    //   '!build/script/crawl_batch/weekly/*',
    //   '!build/app',
    //   '!build/app/public',
    //   '!build/app/public/data',
    //   '!build/app/public/data/images',
    //   '!build/app/public/data/images/*',
    //   '!build/app/public/data/thumbnails',
    //   '!build/app/public/data/thumbnails/*',
    //   '!build/app/public/data/videos',
    //   '!build/app/public/data/videos/*',
    // ],
  },
  serve: {
    dest: './build/app',
  },
  watch: {
    server_js_copy: [`${relativeSrcPath}/**/*.js`, `!${relativeSrcPath + app_front}/**/*.js`],
    coffee_app_public: `${relativeSrcPath + app_front}/**/*.coffee`,
    sass: `${relativeSrcPath + app_front}/sass/**`,
    jade_copy: `${relativeSrcPath + app}/views/**`,
    images_copy: `${relativeSrcPath + app_front}/images/**`,
    mocha: `${relativeTestPath}/**/*.coffee`,
  },
};

// ---
// generated by coffee-script 1.9.2
